### ISSUE TITLE
Static arrays

### ISSUE THREAD

**Issue by webanck** [gwiazdorrr/CxxSwizzle#5]
Firstly, thanks for this library which let me compile most of my shadertoy shaders in c++.

Would you have any trick to compile static arrays such as in the following code?
```
float VALUES[] = float[](1., 2., 3., 4., 5., 6., 7., 8.);
//instead of c++:
//float VALUES[] = {1., 2., 3., 4., 5., 6., 7., 8.};

int nbValues()
{
    return VALUES.length();
}
float[] f()
{
    return float[](1., 2., 3., 4., 5., 6., 7., 8.);
}
//instead of c++:
float * f()
{
    return new float[8]{1., 2., 3., 4., 5., 6., 7., 8.};
}
```

**Comment by gwiazdorrr** [comment]
Sorry for the delay, don't know how I missed this.

Arrays are so damn different in GLSL that you are going to need a macro I am afraid. There's a modernisation branch that I am going to merge in soon that addresses that, have a look!

**Comment by gwiazdorrr** [comment]
This has been solved with the merge.
